# Generated by Django 5.0.6 on 2024-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=20)),
                ('cname', models.CharField(max_length=100)),
                ('clastname', models.CharField(max_length=100)),
                ('cemail', models.EmailField(max_length=254)),
                ('cphone', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
